import {collectConfig,validate,hasSafetyBypass} from './validator.js?v=3';
import {prepare,formatPattern} from './constraints.js';
import {$,$$,formatNumber,formatTime,setText,showError,clearError} from './ui.js';
import './auth.js';
let worker=null;let currentModel=null;let startedAt=0;let elapsedTimer=null;let patternLength=0;let searchPhase='idle';let previewCount=null;
const TYPES=[['any','Any'],['upper','A-Z'],['lower','a-z'],['digit','0-9'],['symbol','Symbol'],['space','Space'],['specific','Specific character']];
function positionSlot(index,existing={type:'any',value:''}){const wrap=document.createElement('div');wrap.className='pattern-slot';wrap.innerHTML=`<label>Position ${index+1}</label><select class="position-type">${TYPES.map(([value,label])=>`<option value="${value}" ${existing.type===value?'selected':''}>${label}</option>`).join('')}</select><input class="specific-value" maxlength="1" value="${existing.value||''}" placeholder="char" ${existing.type==='specific'?'':'hidden'}>`;const select=wrap.querySelector('select');const input=wrap.querySelector('input');select.addEventListener('change',()=>{input.hidden=select.value!=='specific';schedulePreview()});input.addEventListener('input',schedulePreview);return wrap}
function rebuildPattern(length,keep=true){const builder=$('#pattern-builder');const old=keep?$$('.pattern-slot').map(slot=>({type:slot.querySelector('.position-type').value,value:slot.querySelector('.specific-value').value})):[];builder.innerHTML='';for(let i=0;i<length;i++)builder.append(positionSlot(i,old[i]||{type:'any',value:''}));patternLength=length}
function syncLengthMode(){const mode=document.querySelector('input[name="length-mode"]:checked').value;const exact=mode==='exact';$('#length-exact').disabled=!exact;$('#length-min').disabled=exact;$('#length-max').disabled=exact;rebuildPattern(Number(exact?$('#length-exact').value:$('#length-max').value)||0)}
function syncAdminLengthLimit(){const max=hasSafetyBypass()?64:32;['#length-exact','#length-min','#length-max'].forEach(selector=>$(selector).max=max)}
function preview(){previewCount=null;setText('#candidate-count','—');setText('#workload','Ready to validate');setText('#preview-note','Candidate count and constraints are validated when Start is pressed.');$('#start-search').disabled=false}
function formatCandidateCount(value){if(value==='OVERFLOW')return '> 18,446,744,073,709,551,615';try{return BigInt(value).toLocaleString('en-US')}catch{return String(value)}}
function serializePossibility(model){const counts=Object.values(model.counts).flatMap(c=>[c.min,c.max]).join(',');const slots=model.slots.map(slot=>slot.domains.map(domain=>domain.join('')).join('\x1e')).join('\x1f');return [model.allowRepeat?1:0,model.maxOccurrence,model.allowConsecutive?1:0,counts,slots].join('|')}
async function calculatePreview(){clearTimeout(previewTimer);const model=prepare(collectConfig(document));if(model.errors.length){previewCount=null;setText('#candidate-count','0');setText('#workload','Needs attention');setText('#preview-note',model.errors[0]);return}setText('#candidate-count','Calculating...');const previewWorker=new Worker('/js/search-worker.js?v=7',{type:'module'});previewWorker.onmessage=event=>{const data=event.data;if(data.type==='error'){previewWorker.terminate();previewCount=null;setText('#candidate-count','0');setText('#workload','Needs attention');setText('#preview-note',data.message);return}if(data.type!=='countResult')return;previewWorker.terminate();if(data.overflow){previewCount='OVERFLOW';setText('#candidate-count','Too many possibilities / OVERFLOW');setText('#workload','Very high');return}previewCount=data.count;const count=BigInt(data.count);setText('#candidate-count',formatCandidateCount(data.count));setText('#workload',count<10000n?'Low':count<300000n?'Moderate':'High');setText('#preview-note',`Pattern: ${formatPattern(model)}`)};previewWorker.postMessage({type:'count',countConfig:serializePossibility(model)})}
let previewTimer;function schedulePreview(){clearTimeout(previewTimer);previewTimer=setTimeout(preview,80)}
function setRunning(running){$('#start-search').disabled=running;$('#pause-search').disabled=!running;$('#stop-search').disabled=!running;$('#resume-search').disabled=true}
function resetMonitor(){setText('#tested','0');setText('#progress','0%');setText('#speed','0 / sec');setText('#remaining','--');$('#result').hidden=true}
function updateProgress(data){const tested=BigInt(String(data.tested||0));const total=data.total?BigInt(String(data.total)):0n;const progress=total?Number((tested*1000n)/total)/10:0;setText('#tested',formatCandidateCount(String(tested)));setText('#progress',`${Math.min(100,progress).toFixed(1)}%`);setText('#speed',`${formatNumber(Math.round(data.speed))} / sec`);setText('#remaining',total?formatCandidateCount(String(total>tested?total-tested:0n)):'--');setText('#elapsed',formatTime(data.elapsed))}
function finish(data){clearInterval(elapsedTimer);worker?.terminate();worker=null;setRunning(false);$('#pause-search').disabled=true;$('#resume-search').disabled=true;const hasMatches=data.matches.length>0;const limited=data.reason==='timeout'||data.reason==='time'||data.reason==='limit'||data.reason==='possibility';const labels={complete:'No match found.',timeout:'Time limit reached.',time:'Time limit reached.',user:'Search stopped.',limit:'Possibility limit reached.',possibility:'Possibility limit reached.',match:'Possible matches','match-limit':'Possible matches'};setText('#search-status',hasMatches?'Possible matches':(labels[data.reason]||'Search complete'));$('#status-dot').className=`status-dot ${limited||data.reason==='user'?'stopped':'idle'}`;updateProgress(data);const result=$('#result');result.hidden=false;if(hasMatches){globalThis.recordHashlightSearch?.($('#target-hash').value,data.matches[0]);result.innerHTML=`<h3>${data.matches.length===1?'Match found':'Possible matches'}</h3><ol class="matches">${data.matches.map(match=>`<li><code>${escapeHtml(match)}</code></li>`).join('')}</ol><p>${escapeHtml(data.matches[0])} found at attempt: <code>${formatCandidateCount(String(data.tested))}</code></p><p>These are candidates that produce the supplied hash. A hash match does not prove which candidate was the original input.</p>`}else if(limited){result.innerHTML=`<h3>Search stopped</h3><p>Configured computation limit reached.</p><p>Candidates tested: <code>${formatCandidateCount(String(data.tested))}</code></p>`}else{result.innerHTML=`<h3>No match found</h3><p>Candidates tested: <code>${formatCandidateCount(String(data.tested))}</code></p><p>Time: <code>${formatTime(data.elapsed)}</code></p>`}}
function escapeHtml(value){return value.replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]))}
function serializeSearch(model,timeLimit=30,possibilityLimit=0){const counts=Object.values(model.counts).flatMap(c=>[c.min,c.max]).join(',');const slots=model.slots.map(slot=>slot.domains.map(domain=>domain.join('')).join('\x1e')).join('\x1f');return [timeLimit,possibilityLimit,model.maxMatches,model.allowRepeat?1:0,model.maxOccurrence,model.allowConsecutive?1:0,counts,slots].join('|')}
function start(){clearError();const limits=globalThis.hashlightLimits||{timeLimit:30,possibilityLimit:0};const timeLimit=Number(limits.timeLimit);const possibilityLimit=Number(limits.possibilityLimit);if(!Number.isFinite(timeLimit)||timeLimit<=0||(!Number.isFinite(possibilityLimit)||possibilityLimit< -1||possibilityLimit===0)){showError('Search is disabled by the current account or non-login limits.');return}const raw=collectConfig(document);const result=validate(raw);if(result.errors.length){showError(result.errors.join(' '));return}currentModel=result.model;setText('#candidate-count',previewCount?formatCandidateCount(previewCount):'—');setText('#workload',previewCount==='OVERFLOW'?'Very high':'Ready');resetMonitor();setRunning(true);$('#status-dot').className='status-dot searching';setText('#search-status','Loading C++ WASM...');startedAt=0;clearInterval(elapsedTimer);elapsedTimer=null;worker=new Worker('/js/search-worker.js?v=7',{type:'module'});worker.onmessage=event=>{const data=event.data;if(data.type==='error'){clearInterval(elapsedTimer);worker?.terminate();worker=null;setRunning(false);$('#status-dot').className='status-dot stopped';showError(data.message);return}if(data.type==='started'){startedAt=performance.now();elapsedTimer=setInterval(()=>setText('#elapsed',formatTime((performance.now()-startedAt)/1000)),50);setText('#search-status','Searching...');return}if(data.type==='progress'||data.type==='paused')updateProgress(data);if(data.type==='paused'){setText('#search-status','Paused');$('#status-dot').className='status-dot paused';$('#pause-search').disabled=true;$('#resume-search').disabled=false}if(data.type==='done')finish(data)};worker.postMessage({type:'start',config:serializeSearch(currentModel,timeLimit,possibilityLimit),target:result.target,total:previewCount})}
function pause(){worker?.postMessage({type:'pause'});setText('#search-status','Pausing...')}
function resume(){worker?.postMessage({type:'resume'});$('#resume-search').disabled=true;$('#pause-search').disabled=false;$('#status-dot').className='status-dot searching';setText('#search-status','Searching...')}
function stop(){worker?.postMessage({type:'stop'});setText('#search-status','Stopping...')}
function loadExample(){const set=(id,value)=>$(id).value=value;set('#length-exact',7);document.querySelector('input[value="exact"]').checked=true;syncLengthMode();['upper','lower','digit','symbol'].forEach(key=>{$(`#source-${key}`).checked=true});$('#source-space').checked=false;set('#symbols','!@#$%^&*()_+-=[]{}');[['upper',1],['lower',2],['digit',3],['symbol',1],['space',0]].forEach(([key,n])=>{set(`#count-${key}-min`,n);set(`#count-${key}-max`,n)});set('#prefix','');set('#suffix','');set('#excluded','zqyo');$('#allow-repeat').checked=false;$('#max-occurrence').disabled=true;$('#allow-consecutive').checked=false;rebuildPattern(7,false);const slots=$$('.pattern-slot');[['specific','R'],['lower',''],['lower',''],['specific','@'],['digit',''],['digit',''],['specific','3']].forEach(([type,value],i)=>{slots[i].querySelector('.position-type').value=type;slots[i].querySelector('.specific-value').value=value;slots[i].querySelector('.specific-value').hidden=type!=='specific'});schedulePreview()}
function bind(){syncAdminLengthLimit();rebuildPattern(0,false);$$('.workspace input,.workspace select').forEach(el=>{if(el.id?.match(/^count-(upper|lower|digit|symbol|space)-(min|max)$/)){const setExplicitZero=()=>{if(el.value==='')el.value='0'};el.addEventListener('focus',setExplicitZero);el.addEventListener('click',setExplicitZero)}el.addEventListener('change',()=>{if(el.id==='allow-repeat')$('#max-occurrence').disabled=!el.checked;if(el.name==='length-mode')syncLengthMode();if(['length-exact','length-min','length-max'].includes(el.id))rebuildPattern(Number(el.value)||0);schedulePreview()})});globalThis.addEventListener('hashlight-limits',syncAdminLengthLimit);$('#search-preview').addEventListener('click',calculatePreview);$('#add-position').addEventListener('click',()=>{if(patternLength<(hasSafetyBypass()?64:32))rebuildPattern(patternLength+1)});$('#start-search').addEventListener('click',start);$('#pause-search').addEventListener('click',pause);$('#resume-search').addEventListener('click',resume);$('#stop-search').addEventListener('click',stop);$('#load-example').addEventListener('click',loadExample);$('#clear-hash').addEventListener('click',()=>{$('#target-hash').value=''});$('#paste-hash').addEventListener('click',async()=>{try{$('#target-hash').value=(await navigator.clipboard.readText()).replace(/\s+/g,'')}catch{showError('Clipboard access was not available. Paste the hash into the field manually.')}});$('#target-hash').addEventListener('input',event=>{event.target.value=event.target.value.replace(/\s+/g,'')});preview()}
bind();
