export const CATEGORIES={upper:{label:'A-Z',chars:'ABCDEFGHIJKLMNOPQRSTUVWXYZ'},lower:{label:'a-z',chars:'abcdefghijklmnopqrstuvwxyz'},digit:{label:'0-9',chars:'0123456789'},symbol:{label:'Symbol',chars:''},space:{label:'Space',chars:' '}};
export const SOURCES={any:'Any',upper:'A-Z',lower:'a-z',digit:'0-9',symbol:'Symbol',space:'Space',specific:'Specific'};
export function cleanHash(value){return value.replace(/\s+/g,'').toLowerCase()}
export function categoryOf(char,symbols){if(char===' ')return'space';if(/[A-Z]/.test(char))return'upper';if(/[a-z]/.test(char))return'lower';if(/[0-9]/.test(char))return'digit';if(symbols.includes(char))return'symbol';return null}
export function buildConfig(raw){const lengthMode=raw.lengthMode||'exact';const exact=Math.max(0,Number(raw.lengthExact)||0);const min=Math.max(0,Number(raw.lengthMin)||0);const max=Math.max(min,Number(raw.lengthMax)||min);const symbols=[...new Set(raw.symbols||'')].join('');const sources={upper:!!raw.sources.upper,lower:!!raw.sources.lower,digit:!!raw.sources.digit,symbol:!!raw.sources.symbol,space:!!raw.sources.space};const counts={};for(const key of Object.keys(CATEGORIES)){const input=raw.counts?.[key]||{};const untouched=input.min===''&&input.max==='';const lo=untouched?0:Math.max(0,Number(input.min)||0);const hi=untouched?(sources[key]?(lengthMode==='range'?max:exact):0):Math.max(lo,Number(input.max)||0);counts[key]={min:lo,max:hi}}return{algorithm:'md5',lengths:lengthMode==='range'?{min,max}:{min:exact,max:exact},maxLength:Math.max(1,Number(raw.maxLength)||32),sources,symbols,counts,prefix:raw.prefix||'',suffix:raw.suffix||'',excluded:new Set([...(raw.excluded||'')]),allowRepeat:!!raw.allowRepeat,maxOccurrence:Math.max(1,Number(raw.maxOccurrence)||1),allowConsecutive:!!raw.allowConsecutive,positions:raw.positions||[],maxMatches:Math.max(1,Math.min(100,Number(raw.maxMatches)||5))}}
export function alphabet(config){const out={upper:CATEGORIES.upper.chars,lower:CATEGORIES.lower.chars,digit:'0123456789',symbol:config.symbols,space:' '};for(const key of Object.keys(out))out[key]=[...out[key]].filter(ch=>!config.excluded.has(ch));return out}
function domainFor(slot,config,alph){if(!slot||slot.type==='any')return Object.entries(alph).filter(([k])=>config.sources[k]).flatMap(([,chars])=>chars);if(slot.type==='specific')return slot.value?[slot.value]:[];return alph[slot.type]||[]}
function validFixedCharacter(ch,config,alph){return !!ch&&!config.excluded.has(ch)&&categoryOf(ch,config.symbols)&&domainFor({type:categoryOf(ch,config.symbols)},config,alph).includes(ch)}
export function prepare(config){const alph=alphabet(config);const errors=[];const slots=[];const totalMin=config.lengths.min,totalMax=config.lengths.max;if(totalMin<1||totalMin>totalMax||totalMax>config.maxLength)errors.push(`Select a length between 1 and ${config.maxLength} characters.`);if(!Object.values(config.sources).some(Boolean))errors.push('Select at least one character source.');if(config.prefix.length>totalMax||config.suffix.length>totalMax||config.prefix.length+config.suffix.length>totalMax)errors.push('Known prefix and suffix do not fit within the requested length.');for(const ch of [...config.prefix,...config.suffix])if(!validFixedCharacter(ch,config,alph))errors.push('Known prefix/suffix contains a character outside the selected sources or exclusions.');for(const key of Object.keys(config.sources))if(config.sources[key]&&alph[key].length===0)errors.push(`${CATEGORIES[key].label} has no available characters after exclusions.`);for(const key of Object.keys(config.counts)){const c=config.counts[key];if(c.max<c.min)errors.push(`${CATEGORIES[key].label} minimum cannot exceed maximum.`);if(c.max>totalMax)errors.push(`${CATEGORIES[key].label} count exceeds the maximum length.`);if(!config.sources[key]&&c.max>0)errors.push(`${CATEGORIES[key].label} count is set, but its source is disabled.`)}if(!errors.length)for(let length=totalMin;length<=totalMax;length++){const fixed=[];for(let i=0;i<length;i++){let value=null;if(i<config.prefix.length)value=config.prefix[i];else if(i>=length-config.suffix.length)value=config.suffix[i-(length-config.suffix.length)];else if(config.positions[i]&&config.positions[i].type==='specific')value=config.positions[i].value;fixed.push(value)}const domains=fixed.map((fixedChar,i)=>fixedChar?[fixedChar]:domainFor(config.positions[i],config,alph));if(domains.some(d=>d.length===0||d.some(ch=>config.excluded.has(ch))))continue;slots.push({length,domains,fixed})}if(!errors.length&&!slots.length)errors.push('No length satisfies the prefix, suffix, and position constraints.');const usedCount=Object.fromEntries(Object.keys(CATEGORIES).map(k=>[k,0]));for(const ch of [...config.prefix,...config.suffix]){const key=categoryOf(ch,config.symbols);if(key)usedCount[key]++}for(const key of Object.keys(config.counts))if(usedCount[key]>config.counts[key].max)errors.push(`${CATEGORIES[key].label} fixed characters exceed its maximum count.`);return{...config,alph,slots,errors}}
export function formatPattern(model){const slot=model.slots[0];if(!slot)return '';return slot.domains.map((d,i)=>slot.fixed[i]|| (d.length===1?d[0]:`[${d.join('')}]`)).join('')}
